### ISSUE TITLE
Gui interface launching the wrong app ID

### ISSUE THREAD

**Issue by Hawkeye273** [SpasticSquirr3l/PalWorld-Self-Hosting#1]
Hi there. So lets start this off my stating that i am not very Code savvy. So i followed a vunch of YouTube guides to get the first set up done. 

So with the all done i was able to launch the server from the GUI app. However for some reason it keeps launching the incorrect ID for the game to run as a dedicated server. 

Any feedback or advice would be great thanks.

**Comment by SpasticSquirr3l** [comment]
I'm trying to follow along here but you don't call an ID to launch the server? You launch PalServer.exe

**Comment by Hawkeye273** [comment]
No, i was using your start server button. So once the cmd window opens the
app it runs is the game itself and not the server files. So instead of
2394010 it runs 164 something.

So my current way to do it is to run steamcmd, login anonymous,  app_run
2394010. I mostly want to use your interface to allow for backups of the
server as we are losing our save data to regularly. So having a a back up
that is done more recently will be a huge help.

**Comment by SpasticSquirr3l** [comment]
I'm new to GitHub as a user, please keep com's here. Did you get this figured out?

"No, i was using your start server button. So once the cmd window opens the
app it runs is the game itself and not the server files. So instead of
2394010 it runs 164 something.

So my current way to do it is to run steamcmd, login anonymous, app_run
2394010. I mostly want to use your interface to allow for backups of the
server as we are losing our save data to regularly. So having a a back up
that is done more recently will be a huge help. "

**Comment by SpasticSquirr3l** [comment]
This could be a quick fix if you only have one server. You could copy/zip "PalServer\Pal\Saved" every X min/hr/day.
